version: "3.8"
services: 
  react-app: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment: 
      - REACT_APP_NAME=react_app
      - REACT_APP_Link=https://sfasolapi.myt-enterprise.com/
    # env_file:
    # - ./.env
    # stdin_open: true (if it doesn't work)
    #tty: true

